spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/streaming
      username: root
      password: 1234
  application:
    name: streaming

logging:
  level:
    org.springframework.r2dbc.core: debug