spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/streaming?characterEncoding=utf8
    username: root
    password: 1234
  application:
    name: streaming

logging:
  level:
    org.springframework.r2dbc.core: debug