CREATE TABLE IF NOT EXISTS MUSIC_FILE
(
    ID         BIGINT AUTO_INCREMENT,
    FILE_NAME  VARCHAR(20)  NOT NULL,
    URL        VARCHAR(200) NOT NULL,
    CREATED_AT DATE         NOT NULL,
    UPDATED_AT DATE,
    PRIMARY KEY (ID)
)